version: "3.8"
services:
  server:
    image: survey-dingdong:1.0.0
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    container_name: server
    hostname: server
    command: /survey-dingdong/docker/api/startup.sh
    ports:
      - "8000:8000"
    tty: true
    depends_on:
      - mysql
    volumes:
      - $PWD:/survey-dingdong
  mysql:
    build:
      context: .
      dockerfile: docker/db/Dockerfile.mysql
    container_name: mysql
    hostname: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./docker/db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysqldb:/var/lib/mysql

  redis:
    image: redis:6.2.6
    container_name: redis
    command: redis-server --port 6379
    restart: always
    ports:
      - "6379:6379"

volumes:
  mysqldb:
