version: "3.8"
services:
  mysql:
    image: mysql:8.0.33
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: devpassword
      MYSQL_DATABASE: survey_dingdong
      MYSQL_ROOT_PASSWORD: admin
      TZ: "Asia/Seoul"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysqldb:/var/lib/mysql

  redis:
    image: redis:6.2.6
    container_name: redis
    command: redis-server --port 6379
    restart: always
    ports:
      - "6379:6379"

volumes:
  mysqldb:
