"""update project title and desc

Revision ID: 017396941c7b
Revises: e5e5d2ad2393
Create Date: 2024-07-15 00:20:32.604386

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "017396941c7b"
down_revision = "e5e5d2ad2393"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "experiment_project",
        "title",
        existing_type=mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=20),
        type_=sa.String(length=64),
        existing_nullable=False,
    )
    op.alter_column(
        "experiment_project",
        "description",
        existing_type=mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=512),
        type_=sa.String(length=1000),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "experiment_project",
        "description",
        existing_type=sa.String(length=1000),
        type_=mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=512),
        existing_nullable=True,
    )
    op.alter_column(
        "experiment_project",
        "title",
        existing_type=sa.String(length=64),
        type_=mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=20),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
