"""remove location

Revision ID: 04785df6dd6b
Revises: e56736b30609
Create Date: 2024-04-16 01:42:52.481705

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "04785df6dd6b"
down_revision = "e56736b30609"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "lat")
    op.drop_column("user", "lng")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("lng", mysql.FLOAT(), nullable=False))
    op.add_column("user", sa.Column("lat", mysql.FLOAT(), nullable=False))
    # ### end Alembic commands ###
