"""init models

Revision ID: 302cd43724b8
Revises: 
Create Date: 2025-02-09 17:21:54.912391

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "302cd43724b8"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password", sa.String(length=255), nullable=True),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("phone_num", sa.String(length=20), nullable=True),
        sa.Column("is_admin", sa.Boolean(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user")),
    )
    op.create_index(
        op.f("ix_74cda3621ed4527e9f4d082372d5ab7c"), "user", ["email"], unique=False
    )
    op.create_index(
        op.f("ix_9f50fd090eef5f7e8302dc0f40260552"),
        "user",
        ["created_at"],
        unique=False,
    )
    op.create_table(
        "user_oauth",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("oauth_id", sa.String(length=255), nullable=False),
        sa.Column(
            "provider",
            sa.Enum(
                "GOOGLE",
                "FACEBOOK",
                "GITHUB",
                "KAKAO",
                "NAVER",
                name="oauthprovidertypeenum",
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name=op.f("fk_e16742b9b59e5181b5da031ae74b4637")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_oauth")),
    )
    op.create_index(
        op.f("ix_8416aed1c66f52a69c59346b08dbb3fc"),
        "user_oauth",
        ["created_at"],
        unique=False,
    )
    op.create_table(
        "workspace",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=20), nullable=False),
        sa.Column("order_no", sa.Integer(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name=op.f("fk_787cf16cd05551488cd49c11cef65e99")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workspace")),
    )
    op.create_index(
        op.f("ix_6525b684a4e657979eb4650ebbb329d7"),
        "workspace",
        ["created_at"],
        unique=False,
    )
    op.create_table(
        "experiment_project",
        sa.Column("workspace_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=64), nullable=False),
        sa.Column("description", sa.String(length=1000), nullable=True),
        sa.Column("start_date", sa.DATE(), nullable=True),
        sa.Column("end_date", sa.DATE(), nullable=True),
        sa.Column("location", sa.String(length=255), nullable=True),
        sa.Column("is_public", sa.Boolean(), nullable=False),
        sa.Column("joined_participants", sa.Integer(), nullable=False),
        sa.Column("max_participants", sa.Integer(), nullable=False),
        sa.Column(
            "experiment_type",
            sa.Enum("ONLINE", "OFFLINE", name="experimenttypeenum"),
            nullable=False,
        ),
        sa.Column("excluded_dates", sa.JSON(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspace.id"],
            name=op.f("fk_0eed9a2e82d65aeca46696d5d09c9d64"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_experiment_project")),
    )
    op.create_index(
        op.f("ix_5112deaa9d5556cb8b604abf8c8b87c4"),
        "experiment_project",
        ["end_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_80ee4452e5fe56b1bbaf9de28c4cae62"),
        "experiment_project",
        ["title"],
        unique=False,
    )
    op.create_index(
        op.f("ix_925d448e32a8569591712907c739337b"),
        "experiment_project",
        ["start_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_e91042846eb65ba7939fa5c82c8002cc"),
        "experiment_project",
        ["created_at"],
        unique=False,
    )
    op.create_table(
        "experiment_timeslot",
        sa.Column("experiment_project_id", sa.Integer(), nullable=False),
        sa.Column("start_time", sa.Time(), nullable=False),
        sa.Column("end_time", sa.Time(), nullable=False),
        sa.Column("max_participants", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["experiment_project_id"],
            ["experiment_project.id"],
            name=op.f("fk_b6f1f2fbcadd5c14908413d2fe01120a"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_experiment_timeslot")),
        sa.UniqueConstraint(
            "experiment_project_id",
            "start_time",
            "end_time",
            name=op.f("uq_c05fbafd6803546999a14bdb81c63636"),
        ),
    )
    op.create_index(
        op.f("ix_1dda0e2bc1de5b70a3e6f189cb1e37d6"),
        "experiment_timeslot",
        ["end_time"],
        unique=False,
    )
    op.create_index(
        op.f("ix_a9384c5d4f145739bdc119350fbb6e88"),
        "experiment_timeslot",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ab1f61df14b5592c9849f8ef10f52a89"),
        "experiment_timeslot",
        ["start_time"],
        unique=False,
    )
    op.create_table(
        "experiment_participant_timeslot",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("experiment_timeslot_id", sa.Integer(), nullable=False),
        sa.Column("experiment_date", sa.DATE(), nullable=False),
        sa.Column(
            "attendance_status",
            sa.Enum(
                "SCHEDULED",
                "NOT_ATTENDED",
                "ATTENDED",
                name="experimentattendancestatustypeenum",
            ),
            nullable=False,
        ),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["experiment_timeslot_id"],
            ["experiment_timeslot.id"],
            name=op.f("fk_a782e384f01451588ed2d11dbc9d8ab1"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name=op.f("fk_e579b7f331105bbbbb8f245310290220")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_experiment_participant_timeslot")),
    )
    op.create_index(
        op.f("ix_5c2ab0f0884d53459e55bd71a28e923a"),
        "experiment_participant_timeslot",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_73988926089c59f788e478af78d33488"),
        "experiment_participant_timeslot",
        ["experiment_date"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_73988926089c59f788e478af78d33488"),
        table_name="experiment_participant_timeslot",
    )
    op.drop_index(
        op.f("ix_5c2ab0f0884d53459e55bd71a28e923a"),
        table_name="experiment_participant_timeslot",
    )
    op.drop_table("experiment_participant_timeslot")
    op.drop_index(
        op.f("ix_ab1f61df14b5592c9849f8ef10f52a89"), table_name="experiment_timeslot"
    )
    op.drop_index(
        op.f("ix_a9384c5d4f145739bdc119350fbb6e88"), table_name="experiment_timeslot"
    )
    op.drop_index(
        op.f("ix_1dda0e2bc1de5b70a3e6f189cb1e37d6"), table_name="experiment_timeslot"
    )
    op.drop_table("experiment_timeslot")
    op.drop_index(
        op.f("ix_e91042846eb65ba7939fa5c82c8002cc"), table_name="experiment_project"
    )
    op.drop_index(
        op.f("ix_925d448e32a8569591712907c739337b"), table_name="experiment_project"
    )
    op.drop_index(
        op.f("ix_80ee4452e5fe56b1bbaf9de28c4cae62"), table_name="experiment_project"
    )
    op.drop_index(
        op.f("ix_5112deaa9d5556cb8b604abf8c8b87c4"), table_name="experiment_project"
    )
    op.drop_table("experiment_project")
    op.drop_index(op.f("ix_6525b684a4e657979eb4650ebbb329d7"), table_name="workspace")
    op.drop_table("workspace")
    op.drop_index(op.f("ix_8416aed1c66f52a69c59346b08dbb3fc"), table_name="user_oauth")
    op.drop_table("user_oauth")
    op.drop_index(op.f("ix_9f50fd090eef5f7e8302dc0f40260552"), table_name="user")
    op.drop_index(op.f("ix_74cda3621ed4527e9f4d082372d5ab7c"), table_name="user")
    op.drop_table("user")
    # ### end Alembic commands ###
