"""add phone_num col

Revision ID: 349ae9fdd818
Revises: 26621970b947
Create Date: 2024-05-22 01:47:47.464408

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "349ae9fdd818"
down_revision = "26621970b947"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("phone_num", sa.String(length=20), nullable=False))
    op.alter_column(
        "user",
        "username",
        existing_type=mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=255),
        type_=sa.String(length=64),
        existing_nullable=False,
    )
    op.create_unique_constraint(None, "user", ["phone_num"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user", type_="unique")
    op.alter_column(
        "user",
        "username",
        existing_type=sa.String(length=64),
        type_=mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=255),
        existing_nullable=False,
    )
    op.drop_column("user", "phone_num")
    # ### end Alembic commands ###
