"""change nickname to username

Revision ID: 3791c4cb9f95
Revises: 26621970b947
Create Date: 2024-05-12 10:41:08.718875

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "3791c4cb9f95"
down_revision = "26621970b947"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("username", sa.String(length=255), nullable=False))
    op.drop_index("nickname", table_name="user")
    op.create_unique_constraint(None, "user", ["username"])
    op.drop_column("user", "nickname")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("nickname", mysql.VARCHAR(length=255), nullable=False)
    )
    op.drop_constraint(None, "user", type_="unique")
    op.create_index("nickname", "user", ["nickname"], unique=True)
    op.drop_column("user", "username")
    # ### end Alembic commands ###
