"""delete project random code

Revision ID: 73e1cb9ee15e
Revises: 77eaef37f4eb
Create Date: 2024-06-13 01:23:55.050362

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "73e1cb9ee15e"
down_revision = "77eaef37f4eb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("experiment_project", "participant_code")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "experiment_project",
        sa.Column(
            "participant_code",
            mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=4),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###
