"""change phone_num col nullable

Revision ID: 753a23f41b35
Revises: 349ae9fdd818
Create Date: 2024-05-22 01:54:59.469472

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "753a23f41b35"
down_revision = "349ae9fdd818"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user",
        "phone_num",
        existing_type=mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=20),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user",
        "phone_num",
        existing_type=mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=20),
        nullable=False,
    )
    # ### end Alembic commands ###
