"""add role cole to user

Revision ID: 76faf768d6d6
Revises: 6f61d7ff6c84
Create Date: 2025-01-17 02:15:15.844009

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "76faf768d6d6"
down_revision = "6f61d7ff6c84"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "experiment_participant_timeslot",
        "created_at",
        existing_type=mysql.DATETIME(),
        type_=sa.TIMESTAMP(),
        existing_nullable=False,
    )
    op.alter_column(
        "experiment_participant_timeslot",
        "updated_at",
        existing_type=mysql.DATETIME(),
        type_=sa.TIMESTAMP(),
        existing_nullable=False,
    )
    op.alter_column(
        "experiment_project",
        "excluded_dates",
        existing_type=mysql.JSON(),
        nullable=False,
    )
    op.alter_column(
        "experiment_project",
        "created_at",
        existing_type=mysql.DATETIME(),
        type_=sa.TIMESTAMP(),
        existing_nullable=False,
    )
    op.alter_column(
        "experiment_project",
        "updated_at",
        existing_type=mysql.DATETIME(),
        type_=sa.TIMESTAMP(),
        existing_nullable=False,
    )
    op.drop_index("idx_workspace_id_title", table_name="experiment_project")
    op.create_index(
        op.f("ix_experiment_project_title"),
        "experiment_project",
        ["title"],
        unique=False,
    )
    op.create_index(
        op.f("ix_experiment_project_workspace_id"),
        "experiment_project",
        ["workspace_id", "title"],
        unique=False,
    )
    op.alter_column(
        "experiment_timeslot",
        "created_at",
        existing_type=mysql.DATETIME(),
        type_=sa.TIMESTAMP(),
        existing_nullable=False,
    )
    op.alter_column(
        "experiment_timeslot",
        "updated_at",
        existing_type=mysql.DATETIME(),
        type_=sa.TIMESTAMP(),
        existing_nullable=False,
    )
    op.add_column(
        "user",
        sa.Column(
            "role",
            sa.Enum("Researcher", "Participant", name="userroleenum"),
            nullable=False,
        ),
    )
    op.alter_column(
        "user",
        "created_at",
        existing_type=mysql.DATETIME(),
        type_=sa.TIMESTAMP(),
        existing_nullable=False,
    )
    op.alter_column(
        "user",
        "updated_at",
        existing_type=mysql.DATETIME(),
        type_=sa.TIMESTAMP(),
        existing_nullable=False,
    )
    op.alter_column(
        "user_oauth",
        "created_at",
        existing_type=mysql.DATETIME(),
        type_=sa.TIMESTAMP(),
        existing_nullable=False,
    )
    op.alter_column(
        "user_oauth",
        "updated_at",
        existing_type=mysql.DATETIME(),
        type_=sa.TIMESTAMP(),
        existing_nullable=False,
    )
    op.alter_column(
        "workspace",
        "created_at",
        existing_type=mysql.DATETIME(),
        type_=sa.TIMESTAMP(),
        existing_nullable=False,
    )
    op.alter_column(
        "workspace",
        "updated_at",
        existing_type=mysql.DATETIME(),
        type_=sa.TIMESTAMP(),
        existing_nullable=False,
    )
    op.drop_index("ix_workspace_user_id", table_name="workspace")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("ix_workspace_user_id", "workspace", ["user_id"], unique=False)
    op.alter_column(
        "workspace",
        "updated_at",
        existing_type=sa.TIMESTAMP(),
        type_=mysql.DATETIME(),
        existing_nullable=False,
    )
    op.alter_column(
        "workspace",
        "created_at",
        existing_type=sa.TIMESTAMP(),
        type_=mysql.DATETIME(),
        existing_nullable=False,
    )
    op.alter_column(
        "user_oauth",
        "updated_at",
        existing_type=sa.TIMESTAMP(),
        type_=mysql.DATETIME(),
        existing_nullable=False,
    )
    op.alter_column(
        "user_oauth",
        "created_at",
        existing_type=sa.TIMESTAMP(),
        type_=mysql.DATETIME(),
        existing_nullable=False,
    )
    op.alter_column(
        "user",
        "updated_at",
        existing_type=sa.TIMESTAMP(),
        type_=mysql.DATETIME(),
        existing_nullable=False,
    )
    op.alter_column(
        "user",
        "created_at",
        existing_type=sa.TIMESTAMP(),
        type_=mysql.DATETIME(),
        existing_nullable=False,
    )
    op.drop_column("user", "role")
    op.alter_column(
        "experiment_timeslot",
        "updated_at",
        existing_type=sa.TIMESTAMP(),
        type_=mysql.DATETIME(),
        existing_nullable=False,
    )
    op.alter_column(
        "experiment_timeslot",
        "created_at",
        existing_type=sa.TIMESTAMP(),
        type_=mysql.DATETIME(),
        existing_nullable=False,
    )
    op.drop_index(
        op.f("ix_experiment_project_workspace_id"), table_name="experiment_project"
    )
    op.drop_index(op.f("ix_experiment_project_title"), table_name="experiment_project")
    op.create_index(
        "idx_workspace_id_title",
        "experiment_project",
        ["workspace_id", "title"],
        unique=False,
    )
    op.alter_column(
        "experiment_project",
        "updated_at",
        existing_type=sa.TIMESTAMP(),
        type_=mysql.DATETIME(),
        existing_nullable=False,
    )
    op.alter_column(
        "experiment_project",
        "created_at",
        existing_type=sa.TIMESTAMP(),
        type_=mysql.DATETIME(),
        existing_nullable=False,
    )
    op.alter_column(
        "experiment_project",
        "excluded_dates",
        existing_type=mysql.JSON(),
        nullable=True,
    )
    op.alter_column(
        "experiment_participant_timeslot",
        "updated_at",
        existing_type=sa.TIMESTAMP(),
        type_=mysql.DATETIME(),
        existing_nullable=False,
    )
    op.alter_column(
        "experiment_participant_timeslot",
        "created_at",
        existing_type=sa.TIMESTAMP(),
        type_=mysql.DATETIME(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
