"""add is_deleted col to user

Revision ID: 77eaef37f4eb
Revises: 753a23f41b35
Create Date: 2024-06-02 10:56:21.846768

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "77eaef37f4eb"
down_revision = "753a23f41b35"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("is_deleted", sa.Boolean(), nullable=False))
    op.drop_index("email", table_name="user")
    op.drop_index("phone_num", table_name="user")
    op.drop_index("username", table_name="user")
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.create_index("username", "user", ["username"], unique=True)
    op.create_index("phone_num", "user", ["phone_num"], unique=True)
    op.create_index("email", "user", ["email"], unique=True)
    op.drop_column("user", "is_deleted")
    # ### end Alembic commands ###
