"""allow nullable true in project table

Revision ID: 7aaeb7869a43
Revises: 5ca10b8a1ad4
Create Date: 2024-05-03 01:41:15.105337

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "7aaeb7869a43"
down_revision = "5ca10b8a1ad4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "experiment_project", "start_date", existing_type=sa.DATE(), nullable=True
    )
    op.alter_column(
        "experiment_project", "end_date", existing_type=sa.DATE(), nullable=True
    )
    op.alter_column(
        "experiment_project",
        "excluded_dates",
        existing_type=mysql.JSON(),
        nullable=True,
    )
    op.alter_column(
        "experiment_project",
        "location",
        existing_type=mysql.VARCHAR(length=255),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "experiment_project",
        "location",
        existing_type=mysql.VARCHAR(length=255),
        nullable=False,
    )
    op.alter_column(
        "experiment_project",
        "excluded_dates",
        existing_type=mysql.JSON(),
        nullable=False,
    )
    op.alter_column(
        "experiment_project", "end_date", existing_type=sa.DATE(), nullable=False
    )
    op.alter_column(
        "experiment_project", "start_date", existing_type=sa.DATE(), nullable=False
    )
    # ### end Alembic commands ###
