"""update column options

Revision ID: e56736b30609
Revises: 640c73fa2c12
Create Date: 2024-04-16 01:25:47.688419

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "e56736b30609"
down_revision = "640c73fa2c12"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "experiment_project",
        "description",
        existing_type=mysql.VARCHAR(length=512),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "experiment_project",
        "description",
        existing_type=mysql.VARCHAR(length=512),
        nullable=False,
    )
    # ### end Alembic commands ###
