"""create user oauth table

Revision ID: e5e5d2ad2393
Revises: e6dabd74a864
Create Date: 2024-07-07 17:10:47.436243

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "e5e5d2ad2393"
down_revision = "e6dabd74a864"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_oauth",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("oauth_id", sa.String(length=255), nullable=False),
        sa.Column(
            "provider",
            sa.Enum(
                "GOOGLE",
                "FACEBOOK",
                "GITHUB",
                "KAKAO",
                "NAVER",
                name="oauthprovidertypeenum",
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_oauth_created_at"), "user_oauth", ["created_at"], unique=False
    )
    op.alter_column(
        "user",
        "password",
        existing_type=mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=255),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user",
        "password",
        existing_type=mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=255),
        nullable=False,
    )
    op.drop_index(op.f("ix_user_oauth_created_at"), table_name="user_oauth")
    op.drop_table("user_oauth")
    # ### end Alembic commands ###
