"""add filter title to project

Revision ID: e6dabd74a864
Revises: 73e1cb9ee15e
Create Date: 2024-06-25 02:19:58.092945

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e6dabd74a864"
down_revision = "73e1cb9ee15e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "idx_workspace_id_title",
        "experiment_project",
        ["workspace_id", "title"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "experiment_project_ibfk_1", "experiment_project", type_="foreignkey"
    )
    op.drop_index("idx_workspace_id_title", table_name="experiment_project")

    op.create_foreign_key(
        "experiment_project_ibfk_1",
        "experiment_project",
        "workspace",
        ["workspace_id"],
        ["id"],
    )
    # ### end Alembic commands ###
